---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/english/notice
  label: notice
  create: all
  match: "**/*"
- type: directory
  path: content/english/event
  label: events
  create: all
  match: "**/*"
- type: directory
  path: content/english/course
  label: courses
  create: all
  match: "**/*"
- type: directory
  path: content/english/about
  label: about
  create: all
  match: "**/*"
- type: document
  path: config.toml
  label: config
- type: document
  path: data/en/homepage.yml
  label: homepage
upload_dir: static/images
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
